apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app1
  namespace: default
  labels:
    app:  app1
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app:  app1
    spec:
      containers:
      - name:  app1
        image:  samuelkadima/dcatk-workshop:v1.0.0
        ports:
        - containerPort:  8000
          name:  app1
---

apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
spec:
  selector:
    app: app1
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30001
    
